# Generated by Django 4.2.1 on 2023-06-26 12:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Approach',
            },
        ),
        migrations.CreateModel(
            name='Huts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hut_name', models.CharField(max_length=40)),
                ('hut_owner', models.CharField(max_length=80)),
                ('hut_care_taker', models.CharField(max_length=40)),
                ('phone_contact', models.CharField(max_length=20)),
                ('hut_area', models.CharField(blank=True, max_length=60, null=True)),
                ('altitude', models.CharField(blank=True, max_length=5, null=True)),
                ('accommodation_beds', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='huts')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('approach', models.ManyToManyField(to='huts.approach')),
            ],
            options={
                'verbose_name_plural': 'Huts',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Month',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Weather Condition',
            },
        ),
        migrations.CreateModel(
            name='HutsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.huts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HutsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('huts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.huts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='huts',
            name='opened_in',
            field=models.ManyToManyField(to='huts.month'),
        ),
        migrations.AddField(
            model_name='huts',
            name='services',
            field=models.ManyToManyField(to='huts.services'),
        ),
        migrations.AddField(
            model_name='huts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='huts',
            name='weather_condition',
            field=models.ManyToManyField(to='huts.weathercondition'),
        ),
    ]
