# Generated by Django 4.2.1 on 2023-06-08 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hut_name', models.CharField(max_length=40)),
                ('hut_owner', models.CharField(max_length=80)),
                ('hut_care_taker', models.CharField(max_length=40)),
                ('phone_contact', models.CharField(max_length=20)),
                ('hut_area', models.CharField(blank=True, max_length=60, null=True)),
                ('altitude', models.CharField(blank=True, max_length=5, null=True)),
                ('accommodation_beds', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('approach', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PEDESTRIAN', 'Pedestrian'), ('WHEEL', 'Wheel'), ('CAR', 'Car'), ('BUS', 'Bus'), ('LIFT', 'Lift'), ('CAMPER', 'Camper')], max_length=10, null=True)),
                ('weather_forecast', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SUNNY', 'Sunny'), ('CLOUDY', 'Cloudy'), ('RAINY', 'Rainy'), ('SNOWY', 'Snowy')], max_length=6, null=True)),
                ('opened_in', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('JANUARY', 'Jan'), ('FEBRUARY', 'Feb'), ('MARCH', 'Mar'), ('APRIL', 'Apr'), ('MAY', 'May'), ('JUNE', 'Jun'), ('JULY', 'Jul'), ('AUGUST', 'Aug'), ('SEPTEMBER', 'Sep'), ('OCTOBER', 'Oct'), ('NOVEMBER', 'Nov'), ('DECEMBER', 'Dec')], max_length=9, null=True)),
                ('services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('KITCHEN', 'Kitchen'), ('CENTRAL_HEATING', 'Central Heating'), ('FIREPLACE', 'Fireplace'), ('WIFI', 'WiFi'), ('TV', 'TV'), ('ROOM_WITH_BATHROOM', 'Room with Bathroom'), ('SHARED_BATHROOM', 'Shared Bathroom'), ('ROOM_WITH_TOILET', 'Room with Toilet'), ('SHARED_TOILET', 'Shared Toilet'), ('SAUNA', 'Sauna'), ('BBQ_AREA', 'BBQ Area'), ('PLAYGROUND', 'Playground'), ('LAUNDRY_FACILITIES', 'Laundry Facilities'), ('BALCONY', 'Balcony')], max_length=18, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='huts')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HutsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.huts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HutsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=180, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('huts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huts.huts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
