# Generated by Django 4.2.1 on 2023-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huts',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
