# Generated by Django 4.2.1 on 2023-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0002_alter_huts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huts',
            name='publication_date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
