# Generated by Django 4.2.1 on 2023-06-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0002_alter_huts_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='huts',
            name='approach',
        ),
        migrations.AddField(
            model_name='huts',
            name='approach',
            field=models.ManyToManyField(to='huts.approach'),
        ),
    ]
