# Generated by Django 4.2.1 on 2023-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0002_alter_huts_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huts',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
