# Generated by Django 4.2.1 on 2023-06-24 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0003_alter_huts_publication_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huts',
            name='publication_date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
