# Generated by Django 4.2.1 on 2023-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0003_approach_remove_huts_approach_huts_approach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='huts',
            name='weather_forecast',
        ),
        migrations.RemoveField(
            model_name='huts',
            name='opened_in',
        ),
        migrations.RemoveField(
            model_name='huts',
            name='services',
        ),
        migrations.AddField(
            model_name='huts',
            name='weather_condition',
            field=models.ManyToManyField(to='huts.weathercondition'),
        ),
        migrations.AddField(
            model_name='huts',
            name='opened_in',
            field=models.ManyToManyField(to='huts.moth'),
        ),
        migrations.AddField(
            model_name='huts',
            name='services',
            field=models.ManyToManyField(to='huts.services'),
        ),
    ]
