# Generated by Django 4.2.1 on 2023-06-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0004_moth_services_weathercondition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moth',
            new_name='Month',
        ),
    ]
