# Generated by Django 4.2.1 on 2023-06-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huts', '0004_alter_huts_publication_date_and_time'),
        ('huts', '0006_alter_approach_options_alter_month_options_and_more'),
    ]

    operations = [
    ]
